bibli_homepage:
    path:     /bibliotheque
    defaults: { _controller: BibliBundle:Document:index }

document_download:
    path:    /download/{filename}
    defaults: { _controller: BibliBundle:Document:download }