bibli:
    resource: "@BibliBundle/Resources/config/routing.yml"
    prefix:   /

platform:
    resource: "@PlatformBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
