messagerie:
    resource: "@MessagerieBundle/Resources/config/routing.yml"

notification:
    resource: "@NotificationBundle/Resources/config/routing.yml"
    prefix:   /

bibli:
    resource: "@BibliBundle/Resources/config/routing.yml"
    prefix:   /

platform:
    resource: "@PlatformBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
