<?php

namespace PlatformBundle\Repository;

/**
 * Questions_FAQRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Questions_FAQRepository extends \Doctrine\ORM\EntityRepository
{
}
