notification_homepage:
    path:     /
    defaults: { _controller: NotificationBundle:Notification:index }

marks_as_read:
    path:    /markAsRead
    defaults: { _controller: NotificationBundle:Notification:markAsRead }